Provider: Yaml

MySql:
  Host: "127.0.0.1"
  Port: "3306"
  User: "root"
  Database: "xpbank"
  Password: "meeeeooww"

MongoDB:
  Uri: "URI_LINK"
  Database: "xpbank"

Commands:
  Xpbank:
    Name: "xpbank"
    Description: "Manage your experience points in a bank"
    Aliases: [ "xb" ]
